---
- name: Prepare RHEL 10 host for Virtualization and OpenShift
  hosts: all
  become: yes

  vars:
    # used for ocp prep only. reminder to update cli tool if needed. mirror points to z-stream
    ocp_version: "4.18.13"

    rhel_repos:
      - rhel-10-for-x86_64-baseos-rpms
      - rhel-10-for-x86_64-appstream-rpms
      - fast-datapath-for-rhel-10-x86_64-rpms

    rhel_packages:
      - qemu-kvm
      - libvirt
      - virt-install
      - virt-manager
      - virt-viewer
      - libguestfs-tools
      - edk2-ovmf
      - dnsmasq
      - nfs-utils
      - NetworkManager
      - firewalld
      - iproute
      - iputils
      - bind-utils
      - ethtool
      - tcpdump
      - policycoreutils
      - policycoreutils-python-utils
      - selinux-policy
      - selinux-policy-targeted
      - sos
      - psacct
      - kexec-tools
      - bash-completion
      - lsof
      - sysstat
      - dmidecode
      - rsyslog
      - chrony
      - dnf-plugins-core
      - subscription-manager
      - tar
      - gzip
      - bzip2
      - xz
      - unzip
      - curl
      - wget
      - git
      - jq
      - python3
      - lvm2
      - device-mapper-persistent-data
      - parted
      - xfsprogs
      - e2fsprogs
      - podman
      - buildah
      - skopeo
      - crun
      - containers-common
      - slirp4netns
      - fuse-overlayfs
      - conntrack-tools

  tasks:
    - name: Update packages
      dnf:
        name: "*"
        state: latest

    - name: Enable required RH repositories
      command: "subscription-manager repos --enable={{ item }}"
      loop: "{{ rhel_repos }}"
      register: repo_enable
      changed_when: "'enabled' in repo_enable.stdout or 'already' in repo_enable.stdout"

    - name: Install virtualization and system packages
      dnf:
        name: "{{ rhel_packages }}"
        state: present
        update_cache: yes

    - name: Install RHEL group packages
      command: dnf groupinstall -y "Virtualization Host" "Container Management"

    - name: Enable and start core services
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - libvirtd
        - firewalld
        - NetworkManager

    - name: Create working directories
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "/tmp/ocp-{{ ocp_version }}"
        - "/tmp/ocp-{{ ocp_version }}/client"
        - "/tmp/ocp-{{ ocp_version }}/installer"

    - name: Download oc client
      get_url:
        url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/openshift-client-linux.tar.gz"
        dest: "/tmp/ocp-{{ ocp_version }}/client/client.tar.gz"
        mode: "0644"
        force: yes

    - name: Download installer
      get_url:
        url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/openshift-install-linux.tar.gz"
        dest: "/tmp/ocp-{{ ocp_version }}/installer/installer.tar.gz"
        mode: "0644"
        force: yes

    - name: Extract oc client
      unarchive:
        src: "/tmp/ocp-{{ ocp_version }}/client/client.tar.gz"
        dest: "/tmp/ocp-{{ ocp_version }}/client"
        remote_src: yes

    - name: Extract openshift-install
      unarchive:
        src: "/tmp/ocp-{{ ocp_version }}/installer/installer.tar.gz"
        dest: "/tmp/ocp-{{ ocp_version }}/installer"
        remote_src: yes

    - name: Install oc binary
      copy:
        src: "/tmp/ocp-{{ ocp_version }}/client/oc"
        dest: "/usr/local/bin/oc"
        mode: "0755"
        remote_src: yes

    - name: Install kubectl binary
      copy:
        src: "/tmp/ocp-{{ ocp_version }}/client/kubectl"
        dest: "/usr/local/bin/kubectl"
        mode: "0755"
        remote_src: yes

    - name: Install openshift-install binary
      copy:
        src: "/tmp/ocp-{{ ocp_version }}/installer/openshift-install"
        dest: "/usr/local/bin/openshift-install"
        mode: "0755"
        remote_src: yes

    - name: Verify OCP bins
      command: "{{ item }}"
      loop:
        - "/usr/local/bin/oc version"
        - "/usr/local/bin/openshift-install version"
      changed_when: false

    - name: Verify KVM is loaded
      shell: lsmod | grep -q kvm
      register: kvm_check
      failed_when: kvm_check.rc != 0
      changed_when: false

    - name: Update packages
      dnf:
        name: "*"
        state: latest

    - name: Reboot host after installation
      reboot:
        reboot_timeout: 1200
        connect_timeout: 30
        post_reboot_delay: 60  
        test_command: whoami

    - name: Print confirmation
      debug:
        msg: >
          RHEL 10 host fully prepared for virtualization and
          OpenShift {{ ocp_version }}.